version: '3'

services:

  osn__users_backend:
    container_name: osn__users_backend
    hostname: osn__users_backend
    build: service-users/backend
    volumes:
      - ./service-users/backend:/backend
    ports:
      - 3000:3000
    depends_on:
      - osn__users_mysql-master
    environment:
      - DB_MASTER_URL=osn__users_mysql-master:3306
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
      - DB_NAME=dbase
      - SERVER_PORT=3000
    networks:
      - otus-social-network

  osn__users_mysql-master:
    image: 'mysql:5.7'
    hostname: osn__users_mysql-master
    container_name: osn__users_mysql-master
    ports:
      - 3307:3306
    volumes:
      - ./service-users/database/master/conf.d:/etc/mysql/mysql.conf.d
      - ./service-users/database/master/data:/var/lib/mysql
      - ./service-users/database/master/log:/var/log/mysql
      - ./service-users/database/master/backup:/backup
      - ./service-users/database/init_sql:/init_sql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dbase
    networks:
      - otus-social-network

  osn__chat_mongo_shard1:
    image: 'mongo:4.4.1'
    hostname: osn__chat_mongo_shard1
    container_name: osn__chat_mongo_shard1
    ports:
      - 27003:27017
    volumes:
      - ./service-chat/database/shard1/data:/data/db
      - ./service-chat/database/shard1/logs:/var/log/mongodb
      - ./service-chat/database/shard1/mongo.conf:/etc/mongo.conf
      - ./service-chat/database/init:/init
    command: mongod -f /etc/mongo.conf --shardsvr --replSet mongors_shard1 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    networks:
      - otus-social-network

  osn__chat_mongo_shard2:
    image: 'mongo:4.4.1'
    hostname: osn__chat_mongo_shard2
    container_name: osn__chat_mongo_shard2
    ports:
      - 27004:27017
    volumes:
      - ./service-chat/database/shard2/data:/data/db
      - ./service-chat/database/shard2/logs:/var/log/mongodb
      - ./service-chat/database/shard2/mongo.conf:/etc/mongo.conf
      - ./service-chat/database/init:/init
    command: mongod -f /etc/mongo.conf --shardsvr --replSet mongors_shard2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    networks:
      - otus-social-network

  osn__chat_mongocfg:
    image: 'mongo:4.4.1'
    hostname: osn__chat_mongocfg
    container_name: osn__chat_mongocfg
    ports:
      - 27001:27017
    volumes:
      - ./service-chat/database/cfg/data:/data/db
      - ./service-chat/database/cfg/logs:/var/log/mongodb
      - ./service-chat/database/cfg/mongo.conf:/etc/mongo.conf
      - ./service-chat/database/init:/init
    command: mongod -f /etc/mongo.conf --configsvr --replSet mongors_cfg --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    networks:
      - otus-social-network

  osn__chat_mongos:
    image: 'mongo:4.4.1'
    hostname: osn__chat_mongos
    container_name: osn__chat_mongos
    ports:
      - 27100:27017
    command: mongos --configdb mongors_cfg/osn__chat_mongocfg:27017  --port 27017 --bind_ip 0.0.0.0
    volumes:
      - ./service-chat/database/init:/init
    depends_on:
      - osn__chat_mongocfg
      - osn__chat_mongo_shard1
      - osn__chat_mongo_shard2
    networks:
      - otus-social-network

  osn__chat_backend:
    container_name: osn__chat_backend
    hostname: osn__chat_backend
    build: service-chat/backend
    volumes:
      - ./service-chat/backend:/backend
    ports:
      - 3001:3001
    depends_on:
      - osn__chat_mongos
    environment:
      - DB_URL=osn__chat_mongos:27017
      - DB_NAME=chat
      - SERVER_PORT=3001
      - SERVICE_USERS_URL=http://osn__users_backend:3000
    networks:
      - otus-social-network

  osn__nginx:
    container_name: osn_nginx
    image: nginx:latest
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./frontend:/var/www/site
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - osn__users_backend
      - osn__chat_backend
    ports:
      - 8080:80
    networks:
      - otus-social-network

  osn__npm:
    container_name: osn__npm
    build: frontend
    volumes:
      - ./frontend:/frontend

networks:
  otus-social-network:
    external: true
